<a href="https://colab.research.google.com/github/Soulthief3039/HelloWorld/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
tf.keras.layers.Dense(128, activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10, activation='softmax')])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions


array([[0.09811318, 0.1424223 , 0.08153255, 0.10603517, 0.06977683,
        0.10126977, 0.05359579, 0.08718342, 0.13643269, 0.12363835]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09977507, 0.10429543, 0.09813438, 0.10056862, 0.09698749,
        0.10009052, 0.09543075, 0.09869049, 0.1036726 , 0.10235463]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.3016803

In [ ]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8659 - loss: 0.4616
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9560 - loss: 0.1486
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9660 - loss: 0.1098
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9729 - loss: 0.0886
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9772 - loss: 0.0726


In [ ]:
model.evaluate(x_test, y_test, verbose=2)

/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


313/313 - 1s - 2ms/step - accuracy: 0.9759 - loss: 0.0758


[0.07575879245996475, 0.9758999943733215]

In [ ]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:3])


<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[0.08533843, 0.08533832, 0.08534358, 0.08534224, 0.08533832,
        0.08533832, 0.08533832, 0.23194438, 0.08533834, 0.08533977],
       [0.08533696, 0.08533701, 0.23196582, 0.08533747, 0.08533696,
        0.08533747, 0.08533704, 0.08533696, 0.08533734, 0.08533696],
       [0.08534334, 0.23186496, 0.08535215, 0.08534443, 0.08534481,
        0.08534344, 0.0853434 , 0.08536854, 0.08535156, 0.08534334]],
      dtype=float32)>